# Generated by Django 6.0.3 on 2026-03-23 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_delete_employee'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dynamic_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='forms.dynamicform')),
            ],
        ),
    ]
